title: Shelby Hackney - Technical Resume
description: I am a Master of Accountancy student at the University of Tulsa, graduating in May 2019.  Please see below for a compilation of the technical skills and experience I have acquired thus far.

theme: jekyll-theme-modernist
